#!/usr/bin/perl
open FILE, "<codewords.txt";
/^\s*(\d+)\s+([01]+)\s*$/ and $_{chr$1}=$2 while <FILE>;
$/=\1;
while (<STDIN>) {
    $x .= $_{$_};
    print pack 'b*',$1 if $x =~ s/^((?:.{8})+)//;
}
print pack 'b*',$x;
